if("${QEVERCLOUD_FIND_PACKAGE_ARG}" STREQUAL "")
  set(QEVERCLOUD_FIND_PACKAGE_ARG "QUIET")
else()
  set(QEVERCLOUD_FIND_PACKAGE_ARG "")
endif()

QEverCloudFindPackageWrapper(Qt6Core ${QEVERCLOUD_FIND_PACKAGE_ARG})
QEverCloudFindPackageWrapper(Qt6Network ${QEVERCLOUD_FIND_PACKAGE_ARG})
QEverCloudFindPackageWrapper(Qt6Widgets ${QEVERCLOUD_FIND_PACKAGE_ARG})
